### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by gocnpan** [hurshi/wanandroid#4]
无论是自己build的版本，还是下载的release版本，均无法登录，在Android studio run出来的也不能实现登录：
1.点击登录按钮无效；
2.usb调试安装的则会出现：密码中输入“-”符号输入会转移到账号输入栏
并且依旧是点击登录按钮无效。

**Comment by gocnpan** [comment]
E/flutter (27235): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [302]
E/flutter (27235): #0      CommonService.login (package:wanandroid/api/CommonService.dart:77:12)
E/flutter (27235): <asynchronous suspension>
E/flutter (27235): #1      User.login (package:wanandroid/common/User.dart:68:35)
E/flutter (27235): #2      _LoginRegisterPagePageState._buildLoginBtn.<anonymous closure> (package:wanandroid/pages/login/LoginRegisterPage.dart:84:24)
E/flutter (27235): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (27235): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (27235): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (27235): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (27235): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (27235): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (27235): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
E/flutter (27235): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (27235): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (27235): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (27235): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (27235): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (27235): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (27235): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (27235): #17     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (27235): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

**Comment by hurshi** [comment]
#### Hi,感谢你的 issue
* 无法登录是因为 wanandroid 官方把 http 接口升级为 https 了，见 [玩Android 开放API](https://wanandroid.com/blog/show/2)
* 我已经在新的代码中修改过啦，也新传了一个 [release  apk](https://github.com/hurshi/wanandroid/releases/tag/19_03_17),欢迎体验哈。

**Comment by gocnpan** [comment]
> #### Hi,感谢你的 issue
> * 无法登录是因为 wanandroid 官方把 http 接口升级为 https 了，见 [玩Android 开放API](https://wanandroid.com/blog/show/2)
> * 我已经在新的代码中修改过啦，也新传了一个 [release  apk](https://github.com/hurshi/wanandroid/releases/tag/19_03_17),欢迎体验哈。

谢谢，我刚刚登录了wanandroid官网看到了通知，谢谢！
